name: live_audio_room
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0+1

environment:
  sdk: ">=2.16.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  zego_uikit: ^2.27.14
  zego_uikit_prebuilt_live_audio_room: ^3.14.3

  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0
  flutter_screenutil: ">=5.5.3+2 <5.6.1"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0  # run 'flutter pub run import_sorter:main'
  dart_code_metrics: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/avatars/
